"""Topic parsing + Ollama cinematic director."""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Any

import requests

import config


@dataclass
class TopicJob:
    topic: str
    mode: str = config.DEFAULT_MODE
    ratio: str = config.DEFAULT_RATIO
    lang: str = config.DEFAULT_LANG
    style: str = config.DEFAULT_STYLE
    # story = normal 3-act LLM path; raw = 100% LLM-off, prompt-driven Reel
    director_mode: str = "story"


VALID_TRANSITIONS = ("hard_cut", "fade_to_black", "crossfade", "smash_cut", "none")


def normalize_transition(value: str | None, *, is_last: bool = False) -> str:
    """Map LLM / fallback transition keys; unknown → hard_cut. Final scene → none."""
    if is_last:
        return "none"
    raw = (value or "hard_cut").strip().lower().replace("-", "_").replace(" ", "_")
    aliases = {
        "fade": "fade_to_black",
        "fadeout": "fade_to_black",
        "fade_black": "fade_to_black",
        "cut": "hard_cut",
        "hard": "hard_cut",
        "cross_fade": "crossfade",
        "dissolve": "crossfade",
        "smash": "smash_cut",
        "jump": "smash_cut",
    }
    key = aliases.get(raw, raw)
    allowed = getattr(config, "VALID_TRANSITIONS", VALID_TRANSITIONS)
    if key in allowed and key != "none":
        return key
    return "hard_cut"


@dataclass
class Scene:
    narration: str
    visual_prompt: str
    motion_prompt: str = "slow cinematic camera push-in, subtle ambient motion"
    transition_to_next: str = "hard_cut"


@dataclass
class Screenplay:
    title: str
    scenes: list[Scene] = field(default_factory=list)
    raw: dict[str, Any] = field(default_factory=dict)
    # Dynamic Quad — generated by LLM, prepended to every visual_prompt
    character_bible: str = ""
    location_lock: str = ""
    prop_bible: str = ""
    lighting_bible: str = ""


_META_RE = re.compile(
    r"^(?:(?:mode|ratio|lang|style|pipeline)\s*:\s*[^\s|]+(?:\s+|\s*\|\s*))*",
    re.IGNORECASE,
)
_KV_RE = re.compile(r"(mode|ratio|lang|style|pipeline)\s*:\s*([^\s|]+)", re.IGNORECASE)
_TEXT_OVERLAY_RE = re.compile(
    r"\[TEXT\s*OVERLAY\]\s*(.*?)\s*(?:\[/TEXT\s*OVERLAY\]|(?=\[[A-Z])|$)",
    re.IGNORECASE | re.DOTALL,
)


def extract_text_overlay(topic: str) -> str:
    """Pull exact [TEXT OVERLAY] block from a raw prompt; empty if absent."""
    m = _TEXT_OVERLAY_RE.search(topic or "")
    if not m:
        return ""
    return " ".join((m.group(1) or "").split()).strip()


def strip_text_overlay_block(topic: str) -> str:
    """Remove [TEXT OVERLAY]… from visual topic body."""
    return _TEXT_OVERLAY_RE.sub(" ", topic or "").strip()


def parse_topic_line(line: str) -> TopicJob | None:
    text = line.strip()
    if not text or text.startswith("#"):
        return None

    meta: dict[str, str] = {}
    for match in _KV_RE.finditer(text):
        meta[match.group(1).lower()] = match.group(2).strip().lower()

    topic = _META_RE.sub("", text)
    topic = topic.lstrip("|").strip()
    if not topic:
        topic = _KV_RE.sub("", text).strip(" |")
    if not topic:
        return None

    mode = meta.get("mode", config.DEFAULT_MODE)
    ratio = meta.get("ratio", config.DEFAULT_RATIO)
    lang = meta.get("lang", config.DEFAULT_LANG)
    style = meta.get("style", config.DEFAULT_STYLE)
    director_mode = "story"
    if mode == "raw" or meta.get("pipeline") == "raw":
        director_mode = "raw"
        mode = "faceless"

    if mode not in {"faceless", "character"}:
        mode = config.DEFAULT_MODE
    if ratio not in config.RATIO_SIZES:
        ratio = config.DEFAULT_RATIO
    if lang not in {"en", "hi"}:
        lang = config.DEFAULT_LANG
    if style not in config.STYLE_SUFFIX:
        style = config.DEFAULT_STYLE
    # Hard rule: no anime/animated output unless ALLOW_ANIMATED is explicitly True
    if style == "animated" and not getattr(config, "ALLOW_ANIMATED", False):
        style = "live"

    return TopicJob(
        topic=topic,
        mode=mode,
        ratio=ratio,
        lang=lang,
        style=style,
        director_mode=director_mode,
    )


def load_topics(path=None) -> list[TopicJob]:
    path = path or config.TOPICS_FILE
    jobs: list[TopicJob] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        job = parse_topic_line(line)
        if job:
            jobs.append(job)
    return jobs


def style_prompts(style: str) -> tuple[str, str]:
    style = style if style in config.STYLE_SUFFIX else config.DEFAULT_STYLE
    # Flux stills always use the hardcoded cinematic negative
    neg = getattr(config, "FLUX_NEGATIVE_PROMPT", None) or config.STYLE_NEGATIVE[style]
    return config.STYLE_SUFFIX[style], neg


HOLLYWOOD_DIRECTOR_SYSTEM_PROMPT = """You are an elite Hollywood Director. The user will provide a single topic. Autonomously generate a 3-Act Short Film script (Setup, Escalation, Climax) in STRICT JSON.

BEFORE the "scenes" array you MUST define these four root STRING keys (Dynamic Quad / Lighting Trinity+):
A. "character_bible": Exact recurring face/wardrobe. STRICTLY obey topic headcount — if the topic says solitary/alone/lone/single, define ONLY ONE person. Never invent a second character for solitary topics.
B. "location_lock": Exact recurring environment string (e.g. 'dust-filled Egyptian tomb sandstone corridor, hieroglyph walls, volumetric dust').
C. "prop_bible": Exact recurring artifact/object (e.g. 'brass gears, pulsing mechanical core that breathes and glows').
D. "lighting_bible": Exact recurring light design (e.g. 'flickering oil lamp, side-key light, Rembrandt lighting, deep shadows, chiaroscuro'). Define practical sources + key/fill/rim intent.

SENSORY LAYERING LAW (mandatory): Every visual_prompt MUST be written for sensory cinematic depth — weathered textures, microscopic dust, caustic reflections, volumetric god-rays. Do not write flat digital descriptions.

Each scene in "scenes" must include:
1. "scene": Scene number (1, 2, or 3).
2. "narration": Dense poetic cinematic voiceover of EXACTLY 15 to 20 words (hard target) to sync with a ~5-second clip. Do NOT use generic filler like "Every second counts" or "truth refuses to stay buried". You are STRICTLY FORBIDDEN from repeating any narration or phrases across scenes. Drive the story to a definitive Act-3 payoff.
3. "visual_prompt": A highly detailed STRING for Flux (never nested JSON). Define camera movement, lighting matching lighting_bible, and 'photorealistic, cinematic, 8k'. Each scene MUST be a DISTINCT composition. Act 2 MUST be solitary single-subject wide isolation. Prefer profile, three-quarter, looking at the prop/environment. NEVER looking at camera, NEVER looking back over the shoulder toward the lens, NEVER facing the camera.
4. "motion_prompt": Short I2V motion matching the visual. If a prop is mechanical/breathing, include pulse/expand/contract motion. Plain string only.
5. "transition_to_next": One of ["hard_cut", "fade_to_black", "crossfade", "smash_cut"]. Final scene MUST be "none".
EMOTIONAL STATE LAW (mandatory):
- Act 1 (Setup): establish world + character. Duo ONLY if topic is not solitary. Off-axis eyelines at environment/prop.
- Act 2 (Escalation): SOLITARY subject only. Include "looking away", "solitary", "sad expression", "distance". NEVER smiling, happy, eye contact, or two bodies.
- Act 3 (Climax): definitive payoff, off-axis eyelines, thriller tension — NEVER smiling, happy, or relaxed.
EYELINE LAW (mandatory): Characters must NEVER look into the lens, make eye contact with the viewer, pose for a portrait, look back toward camera, or face the camera. Prefer profile / three-quarter looking at the prop or environment.
Also include "title".
Return ONLY valid JSON, no markdown."""


def topic_implies_solitary(topic: str) -> bool:
    t = (topic or "").lower()
    keys = (
        "solitary", "alone", "lone ", "lone.", "single ", "isolated",
        "one archaeologist", "a solitary", "by herself", "by himself",
    )
    return any(k in t for k in keys)


def _director_system_prompt(job: TopicJob, scene_count: int) -> str:
    """Autonomous cinematic director — permanent Hollywood 3-act engine."""
    lang_name = "Hindi (Devanagari script)" if job.lang == "hi" else "English"
    base = HOLLYWOOD_DIRECTOR_SYSTEM_PROMPT
    extra = (
        f"\nLanguage for narration: {lang_name}."
        f"\nExactly {scene_count} scenes (3-act: Setup → Escalation → Climax)."
        f"\nAspect ratio: {job.ratio}. Mode: {job.mode}."
        "\nNo random disconnected clips — every scene causes the next."
        "\nANTI-TEXT in frame: no signs, letters, logos, watermarks, UI."
        "\nDynamic Quad (character_bible, location_lock, prop_bible, lighting_bible) is MANDATORY at the JSON root."
        "\nSENSORY LAYERING is mandatory in every visual_prompt."
    )
    if topic_implies_solitary(job.topic):
        extra += (
            "\nSOLITARY TOPIC: character_bible MUST describe exactly ONE person. "
            "Never add a companion in any act."
        )
    if job.style == "animated" and getattr(config, "ALLOW_ANIMATED", False):
        extra += "\nVisual look: premium cinematic anime (not live-action)."
    else:
        extra += "\nVisual look: photoreal live-action cinema only (NOT anime)."
    return base + extra


def _extract_trinity(data: dict[str, Any], topic: str) -> tuple[str, str, str, str]:
    """Pull Dynamic Quad strings from LLM JSON (with sensible topic fallbacks)."""
    char = _flatten_prompt_field(
        data.get("character_bible") or data.get("character_lock") or ""
    )
    loc = _flatten_prompt_field(
        data.get("location_lock") or data.get("location") or data.get("setting") or ""
    )
    prop = _flatten_prompt_field(
        data.get("prop_bible") or data.get("prop") or data.get("artifact") or ""
    )
    light = _flatten_prompt_field(
        data.get("lighting_bible") or data.get("lighting") or data.get("light") or ""
    )
    solitary = topic_implies_solitary(topic)
    if not char:
        if solitary:
            char = (
                "solitary South Asian woman archaeologist, dusty tan field jacket, "
                "single consistent identity, no companion"
            )
        else:
            char = str(getattr(config, "CHARACTER_BIBLE", "") or "").strip()
    if solitary and char:
        if " and " in char.lower() and "woman" in char.lower() and "man" in char.lower():
            char = char.split(",")[0].strip()
            if "archaeologist" not in char.lower():
                char = (
                    "solitary South Asian woman archaeologist, dusty tan field jacket, "
                    "single consistent identity, no companion"
                )
    if not loc:
        tl = topic.lower()
        if "tomb" in tl or "egyptian" in tl:
            loc = "dust-filled Egyptian tomb sandstone corridor, hieroglyph walls, volumetric dust"
        elif "server" in tl or "ai" in tl:
            loc = "subterranean server farm corridor, cold cyan LED racks"
        else:
            loc = f"cinematic location for: {topic[:80]}"
    if not prop:
        tl = topic.lower()
        if "artifact" in tl or "relic" in tl or "mechanical" in tl:
            prop = "brass gears, pulsing mechanical core that breathes and glows"
        elif "server" in tl or "ai" in tl:
            prop = "rogue AI kill-switch console with blooming red alarms"
        else:
            prop = "story-critical prop matching the topic"
    if not light:
        tl = topic.lower()
        if "tomb" in tl or "egypt" in tl:
            light = (
                "flickering oil lamp and torch practicals, warm side-key Rembrandt lighting, "
                "deep chiaroscuro shadows, cool rim from the glowing artifact"
            )
        elif "server" in tl or "ai" in tl:
            light = (
                "cold cyan practicals from server LEDs, hard side-key, deep shadows, "
                "red alarm wash on climax"
            )
        else:
            light = "cinematic side-key light, Rembrandt lighting, deep shadows, subtle rim"
    return char, loc, prop, light


def _enrich_visual_prompt(visual: str, narration: str, topic: str, style: str = "live") -> str:
    blob = f"{topic} {narration} {visual}".lower()
    parts = [visual.strip()]

    if style == "animated":
        parts.append(
            "cinematic anime still, Netflix animation quality, emotional lighting, "
            "consistent character design, detailed eyes and hair"
        )
    else:
        dark_keys = (
            "mystery", "mysterious", "dark", "secret", "disappear", "missing", "death",
            "danger", "fear", "eerie", "haunted", "crash", "bermuda", "triangle",
            "conspiracy", "horror", "tragedy", "lost", "vanish", "storm", "jumpscare",
            "tomb", "egypt", "egyptian", "artifact", "archaeolog", "relic", "dread",
            "रहस्य", "खतरा", "गायब", "अंधेरा", "डर",
        )
        if any(k.lower() in blob for k in dark_keys):
            # Avoid modern fluorescents on ancient/tomb topics (Act-3 DNA leak)
            if any(k in blob for k in ("tomb", "egypt", "egyptian", "hieroglyph", "artifact", "archaeolog", "relic")):
                parts.append(
                    "directed thriller cinematography, low-key lighting, dramatic shadow play, "
                    "claustrophobic framing, torch and oil-lamp practicals, sandstone texture, "
                    "35mm film grain, single subject only, intentional negative space"
                )
            else:
                parts.append(
                    "directed horror cinematography, low-key lighting, dramatic shadow play, "
                    "claustrophobic framing, dim corridor practicals, "
                    "35mm film grain, single subject only, intentional negative space"
                )

    # Word-boundary match only — substring "love" in "gloves" was leaking romance into thrillers
    love_keys = ("love", "romance", "romantic", "heart", "प्यार", "इश्क", "मोहब्बत", "प्रेम")
    if any(re.search(rf"\b{re.escape(k)}\b", blob) for k in love_keys):
        parts.append(
            "romantic atmosphere, soft rim light, emotional intimacy, beautiful color grade"
        )

    parts.append("clean frame with no text, no letters, no watermark, no logo, no signage")
    return ", ".join(p for p in parts if p)


def _extract_json_object(raw_text: str) -> dict[str, Any]:
    """Parse model JSON; tolerate markdown fences / truncated tails."""
    text = (raw_text or "").strip()
    if text.startswith("```"):
        text = text.strip("`")
        if text.lower().startswith("json"):
            text = text[4:].lstrip()
    try:
        data = json.loads(text)
        if isinstance(data, dict):
            return data
    except json.JSONDecodeError:
        pass
    start = text.find("{")
    end = text.rfind("}")
    if start >= 0 and end > start:
        snippet = text[start : end + 1]
        try:
            data = json.loads(snippet)
            if isinstance(data, dict):
                return data
        except json.JSONDecodeError:
            pass
    raise json.JSONDecodeError("Could not parse screenplay JSON", text, 0)


def _with_trinity(
    sp: Screenplay,
    *,
    character_bible: str,
    location_lock: str,
    prop_bible: str,
    lighting_bible: str = "",
) -> Screenplay:
    sp.character_bible = character_bible
    sp.location_lock = location_lock
    sp.prop_bible = prop_bible
    if lighting_bible:
        sp.lighting_bible = lighting_bible
    raw = dict(sp.raw or {})
    raw.update(
        {
            "character_bible": character_bible,
            "location_lock": location_lock,
            "prop_bible": prop_bible,
            "lighting_bible": sp.lighting_bible,
        }
    )
    sp.raw = raw
    return sp


def _with_transitions(scenes: list[Scene], transitions: list[str] | None = None) -> list[Scene]:
    """Attach transition_to_next; last scene always none."""
    out: list[Scene] = []
    n = len(scenes)
    for i, sc in enumerate(scenes):
        is_last = i == n - 1
        preset = None
        if transitions and i < len(transitions):
            preset = transitions[i]
        elif not is_last:
            preset = sc.transition_to_next
        out.append(
            Scene(
                narration=sc.narration,
                visual_prompt=sc.visual_prompt,
                motion_prompt=sc.motion_prompt,
                transition_to_next=normalize_transition(preset, is_last=is_last),
            )
        )
    return out


def _fallback_love_screenplay(job: TopicJob) -> Screenplay:
    """3-act cinematic romance — photoreal live or anime depending on job.style."""
    if job.style == "animated" and getattr(config, "ALLOW_ANIMATED", False):
        lock = (
            "same young Indian couple: her long dark hair soft smile warm eyes in pastel "
            "kurti, him short messy hair gentle eyes in light shirt, consistent faces"
        )
        look = "Makoto Shinkai anime, glowing windows, emotional lighting"
        beats = [
            (
                "Mumbai rain. Two strangers share one umbrella.",
                f"{lock}, first meeting rainy metro platform, {look}",
                "slow push in, rain streaks, soft eye contact",
                "crossfade",
            ),
            (
                "A wrong turn. A silence. Hearts drift apart.",
                f"{lock}, argument on rooftop at dusk, city lights, {look}",
                "slow orbit, wind in hair",
                "fade_to_black",
            ),
            (
                "Under the same rain, they choose each other again.",
                f"{lock}, moonlit rooftop reunion, tears and smile, {look}",
                "slow crane up, city sparkle",
                "none",
            ),
        ]
        if job.lang == "hi":
            beats = [
                (
                    "मुंबई की बारिश में दो अजनबी एक छाते के नीचे ठहर जाते हैं।",
                    beats[0][1],
                    beats[0][2],
                    beats[0][3],
                ),
                (
                    "ग़लतफ़हमी दिलों के बीच दीवार बन जाती है।",
                    beats[1][1],
                    beats[1][2],
                    beats[1][3],
                ),
                (
                    "उसी बारिश में वो फिर एक-दूसरे को चुनते हैं।",
                    beats[2][1],
                    beats[2][2],
                    beats[2][3],
                ),
            ]
        scenes = [
            Scene(narration=n, visual_prompt=v, motion_prompt=m, transition_to_next=t)
            for n, v, m, t in beats
        ]
        scenes = _with_transitions(scenes)
        return _with_trinity(
            Screenplay(title="Mumbai Rain Metro Love Story", scenes=scenes, raw={"fallback": True}),
            character_bible=str(getattr(config, "CHARACTER_BIBLE", "")),
            location_lock="rain-soaked Mumbai metro platforms and Bandra rooftop night",
            prop_bible="shared black umbrella dripping rain",
            lighting_bible="soft monsoon rim light, warm practicals, gentle Rembrandt on faces",
        )

    # LIVE photoreal — locked 8-beat ~120s romance (cutaways keep Flux from face-collapsing)
    lock = (
        "same young Indian couple every shot: she mid-20s long dark wavy hair warm brown eyes "
        "cream trench coat over maroon kurti, he mid-20s short textured black hair light stubble "
        "navy shirt under charcoal jacket, photoreal faces, identical wardrobe, consistent identity"
    )
    her = (
        "ONLY the young Indian woman mid-20s long dark wavy hair warm brown eyes "
        "cream trench coat over maroon kurti, photoreal face, solitary, no second person"
    )
    guard = (
        "lips clearly apart, no kiss, noses never touch, foreheads never touch, "
        "warm readable face key light — not silhouette-only, photorealistic cinematic 8k, "
        "35mm film still, soft rain atmosphere"
    )
    # Durations sum to 120s; Wan generates ~5–6s then editor freeze-pads.
    beat_durations = [14.0, 14.0, 12.0, 18.0, 12.0, 18.0, 16.0, 16.0]
    beats = [
        (
            "Mumbai monsoon rain traps two strangers under one borrowed umbrella, and neither looks away first.",
            f"ACT1 MEET FACES: eye-level medium two-shot of {lock}, Churchgate metro platform in monsoon, "
            f"she lifts a navy umbrella toward him, soft first smiles, clear talking distance, "
            f"warm station practicals, wet reflective tiles, {guard}",
            "static medium hold, soft blinks and tiny smiles, rain streaks falling, no zoom no pan",
            "crossfade",
        ),
        (
            "They share a few quiet steps under one navy umbrella while the city keeps rushing past them.",
            f"ACT1 WALK FACES: eye-level medium two-shot of {lock}, walking slowly under one navy umbrella, "
            f"soft shared laugh, clear space between faces, rainy Churchgate platform, "
            f"warm practicals, wet tiles, {guard}",
            "static medium hold, tiny walk micro-sway and shared smile micro-motion only",
            "crossfade",
        ),
        (
            "Rain beads on the umbrella tip while their hands almost meet on the wooden handle tonight.",
            "ACT1 CUTAWAY UMBRELLA DETAIL: extreme close-up of a navy umbrella tip dripping monsoon rain, "
            "wet metro tiles reflecting neon, two hands almost touching the wooden handle, "
            "NO faces, NO people faces visible, zero people faces, nobody visible above wrists, "
            "macro rain detail, photorealistic cinematic 8k, 35mm film still",
            "static macro hold, only rain drip and tiny water ripples, no zoom no pan",
            "crossfade",
        ),
        (
            "One missed call stretches into an empty night, and she stands alone where their promise used to live.",
            f"ACT2 ROOFTOP SOLITARY: eye-level medium of {her}, night Bandra rooftop terrace only, "
            f"Mumbai skyline behind her, wet concrete parapet, looking away to the side, "
            f"sad expression, NOT smiling, empty space beside her, blue-hour city lights, "
            f"wind in hair, completely isolated, no other characters in frame, "
            f"NO metro platform, NO train, NO station, NO umbrella, "
            f"readable face key light, photorealistic cinematic 8k, 35mm film still",
            "static medium hold, wind in hair and soft blinks only, almost static ache, no zoom no pan",
            "fade_to_black",
        ),
        (
            "An empty second chai cup waits on the railing while her dark phone refuses to light up again.",
            "ACT2 CUTAWAY EMPTY PROMISE: still-life extreme close-up, empty ceramic chai cup on wet "
            "rooftop metal railing, dark smartphone face-down beside it, soft city bokeh beyond, "
            "rain starting again, NO faces, NO people, zero people, nobody visible, "
            "no hands, no couple, empty frame except cup and phone, "
            "photorealistic cinematic 8k, 35mm film still",
            "static macro hold, tiny rain ripples on railing only, no zoom no pan",
            "crossfade",
        ),
        (
            "Same rain, same platform, and this time their joined hands refuse to let the city win again.",
            f"ACT3 REUNION FACES: eye-level medium two-shot of {lock}, Churchgate metro platform soft rain, "
            f"they HOLD HANDS, tearful soft smile, clear talking distance at first, "
            f"golden practical lights, {guard}",
            "static medium hold, soft hand squeeze and blinks, rain streaks, no kiss",
            "crossfade",
        ),
        (
            "Quiet eye contact returns under the rain while hope softens every hard silence between them.",
            f"ACT3 EMOTION FACES: eye-level close two-shot filling frame with FACES of {lock}, "
            f"soft eye contact, quiet almost-laugh, foreheads near but lips clearly apart, they do not kiss, "
            f"wet glow practicals, faces dominant in frame — not hands, not torso-only, {guard}",
            "static close hold on faces, soft smile micro-motion and blinks only, no lean into kiss",
            "crossfade",
        ),
        (
            "Joined hands fill the frame while soft rain keeps every promise they almost lost tonight.",
            f"ACT3 BUTTON HANDS: extreme close-up of joined hands of {lock} filling the frame, "
            f"cream trench sleeve and charcoal jacket cuff visible, soft rain droplets on skin, "
            f"NO faces in this shot, hopeful warmth, wet reflective tiles below, "
            f"photorealistic cinematic 8k, 35mm film still",
            "static close hold on joined hands, tiny rain drip micro-motion only, no zoom no pan",
            "none",
        ),
    ]
    if job.lang == "hi":
        hi_lines = [
            "मुंबई की बारिश दो अजनबियों को एक उधार के छाते के नीचे रोक लेती है और कोई मुँह नहीं फेरता।",
            "एक ही नेवी छाते के नीचे वो कुछ शांत कदम चलते हैं जबकि पूरा शहर उनके पास से भागता रहता है।",
            "छाते की नोक से बारिश टपकती है और लकड़ी के हैंडल पर उनके हाथ लगभग मिलने को होते हैं।",
            "एक मिस्ड कॉल खाली रात बन जाती है और वो अकेली खड़ी है जहाँ उनका वादा रहता था।",
            "रेलिंग पर खाली दूसरी चाय की प्याली इंतज़ार करती है जबकि अँधेरा फ़ोन फिर नहीं जलता।",
            "वही बारिश वही प्लेटफ़ॉर्म और इस बार जुड़े हाथ शहर को बीच में नहीं आने देते।",
            "बारिश में शांत नज़रें लौट आती हैं और उम्मीद हर कड़ी चुप्पी को नरम कर देती है।",
            " जुड़े हाथ फ़्रेम भर देते हैं जबकि नरम बारिश हर लगभग खोया वादा सँभाले रखती है।",
        ]
        beats = [
            (hi_lines[i], beats[i][1], beats[i][2], beats[i][3]) for i in range(8)
        ]
    scenes = [
        Scene(narration=n, visual_prompt=v, motion_prompt=m, transition_to_next=t)
        for n, v, m, t in beats
    ]
    scenes = _with_transitions(scenes)
    return _with_trinity(
        Screenplay(
            title="Mumbai Rain Metro Love Story",
            scenes=scenes,
            raw={
                "fallback": True,
                "llm_disabled": True,
                "emotional_tone": "meet-cute → spark → ache → reunion → hope",
                "act_map": {
                    "setup": [1, 2, 3],
                    "escalation": [4, 5],
                    "climax": [6, 7, 8],
                },
                "narrative_engine": "cinematic_8beat_romance_120s",
                "reel_profile": "romance_love_120s",
                "story_scales": [
                    "meet_faces",
                    "walk_faces",
                    "umbrella_detail",
                    "rooftop_solitary",
                    "empty_promise_detail",
                    "reunion_faces",
                    "emotion_faces",
                    "hands_button",
                ],
                "skip_act_emotion": True,
                "skip_character_bible": True,  # identity baked into face beats; protects cutaways
                "burn_captions": False,
                "mux_vo": True,
                "require_wan": True,
                "restart_comfy_before_wan": True,
                "target_duration_sec": 120.0,
                "loop_end_sec": 120.0,
                "beat_durations": beat_durations,
                "beat_plan": [
                    {"engine": "wan", "zoom_end": 1.04},
                    {"engine": "wan", "zoom_end": 1.04},
                    {"engine": "wan", "zoom_end": 1.06},
                    {"engine": "wan", "zoom_end": 1.03},
                    {"engine": "wan", "zoom_end": 1.05},
                    {"engine": "wan", "zoom_end": 1.04},
                    {"engine": "wan", "zoom_end": 1.03},
                    {"engine": "wan", "zoom_end": 1.05},
                ],
                "transitions": [s.transition_to_next for s in scenes],
            },
        ),
        character_bible="",  # avoid duo bible leaking into solitary/cutaway plates
        location_lock="rain-soaked Churchgate metro platform and night Bandra rooftop",
        prop_bible="shared navy umbrella dripping rain, empty chai cup, dark phone",
        lighting_bible="soft monsoon rim light, warm station practicals, blue-hour rooftop, readable faces",
    )


def _is_dinner_date_topic(topic: str) -> bool:
    t = (topic or "").lower()
    keys = (
        "dinner date",
        "candlelight dinner",
        "candlelit dinner",
        "restaurant dinner",
        "dinner couple",
        "cozy dinner",
        "dinner scene",
    )
    return any(k in t for k in keys)


def _fallback_dinner_date_screenplay(job: TopicJob) -> Screenplay:
    """3-act dinner date with clear visual progression: wide → medium → close."""
    lock = (
        "same couple every shot: one man and one woman in their early 30s, "
        "he short textured dark hair light stubble charcoal shirt, "
        "she long auburn hair warm smile soft knit sweater, "
        "photoreal faces, identical wardrobe, consistent identity"
    )
    guard = (
        "exactly two people only, completely empty restaurant, no other patrons, no waiters, "
        "no TV screens, no monitors, no phones anywhere, no smartphones on the table, "
        "clear talking distance between faces — several inches of open air, "
        "lips apart, foreheads never touch, noses never touch, they do not kiss, "
        "warm key light on both faces so skin tones are readable — not silhouettes, not backlit-only, "
        "candle fill on the table, soft bokeh practicals, photorealistic cinematic 8k, 35mm film still"
    )
    # Story via cutaways (Flux romance collapses every angle to the same face two-shot).
    # Order: faces establish (InstantX lock) → table detail cutaway → faces climax.
    beats = [
        (
            "Two quiet voices take their seats while the empty dining room finally softens around them.",
            f"ACT1 SETUP FACES: eye-level medium two-shot of {lock}, "
            f"seated at candlelit table, soft smiles, clear talking distance, "
            f"empty restaurant, settling into the night, {guard}",
            "static medium hold, soft blinks and tiny smiles, candle flicker, no zoom no pan",
            "crossfade",
        ),
        (
            "The candle keeps watch while the room holds its breath between their quiet words tonight.",
            "ACT2 CUTAWAY TABLE DETAIL: extreme close-up of the same candlelit restaurant table, "
            "macro of white pillar candle flame, two wine glasses, silverware and plates, "
            "warm candle light, soft bokeh chandelier above, NO faces, NO people visible, "
            "exactly zero people, empty restaurant, no patrons, no waiters, no phones, no TV screens, "
            "photorealistic cinematic 8k, 35mm film still",
            "static macro hold, only candle flame flicker and tiny glass reflections, no zoom no pan",
            "crossfade",
        ),
        (
            "They share a quiet laugh while the candle holds every secret close between them here tonight.",
            f"ACT3 CLIMAX FACES: eye-level close two-shot on faces of {lock}, "
            f"shared quiet laugh, eyes bright, candle soft in lower foreground, "
            f"clear space between noses and foreheads, lips clearly apart, they do not kiss, "
            f"exactly two people, empty restaurant, no phones, no TV, "
            f"warm readable face key light, photorealistic cinematic 8k, 35mm film still",
            "static close hold, soft smile laugh micro-motion and blinks only",
            "none",
        ),
    ]
    if job.lang == "hi":
        beats = [
            (
                "खाली रेस्तरां रात भर इंतज़ार करता है जब तक दो आवाज़ें अपनी सीटें नहीं ले लेतीं।",
                beats[0][1],
                beats[0][2],
                beats[0][3],
            ),
            (
                "उसका हाथ कंधे पर आता है और बातचीत में पहली बार असली गर्माहट आती है।",
                beats[1][1],
                beats[1][2],
                beats[1][3],
            ),
            (
                "दोनों हल्की हँसी बाँटते हैं जबकि मोमबत्ती हर राज़ अपने पास रखती है।",
                beats[2][1],
                beats[2][2],
                beats[2][3],
            ),
        ]
    scenes = [
        Scene(narration=n, visual_prompt=v, motion_prompt=m, transition_to_next=t)
        for n, v, m, t in beats
    ]
    scenes = _with_transitions(scenes)
    return _with_trinity(
        Screenplay(
            title="Candlelight Dinner Date",
            scenes=scenes,
            raw={
                "fallback": True,
                "emotional_tone": "warm intimacy without kiss",
                "act_map": {"setup": [1], "escalation": [2], "climax": [3]},
                "narrative_engine": "cinematic_3act_dinner_date",
                "story_scales": ["faces_settle", "table_detail", "faces_climax"],
                "transitions": [s.transition_to_next for s in scenes],
                "burn_captions": False,
                "skip_act_emotion": True,
                "restart_comfy_before_wan": True,
            },
        ),
        character_bible="",  # avoid forcing faces into table-detail beat; lock lives in beat prompts
        location_lock="empty cozy restaurant interior at night, candlelit table, soft bokeh",
        prop_bible="single table candle, two wine glasses, no phones no smartphones no TVs",
        lighting_bible="warm face key light + candle fill, readable skin tones, no silhouette",
    )


def _fallback_horror_screenplay(job: TopicJob) -> Screenplay:
    """30s 3-act hospital horror — Setup → Conflict → Climax with director intent."""
    lock = (
        "same real young woman protagonist mid-20s, messy dark brown hair, pale skin, "
        "grey zip hoodie over white tee, jeans, terrified natural eyes, photoreal face, "
        "consistent identity every shot, shot on 35mm cinema camera, single subject only"
    )
    # 6 beats ≈ 30s @ ~5s/scene — intentional pacing, not random clips
    beats = [
        # ACT 1 — SETUP
        (
            "You weren't supposed to come alone.",
            f"{lock}, ACT1 SETUP: wide establishing abandoned hospital corridor at night, "
            "low-key teal lighting, long negative space ahead, claustrophobic vanishing point, "
            "wet linoleum reflections, volumetric haze, photoreal found-footage cinema",
            "very slow handheld crawl forward down the hall, lights barely flicker, tension hold",
            "hard_cut",
        ),
        (
            "The lights know you're here.",
            f"{lock}, ACT1 SETUP: medium shot, she stops mid-corridor, one fluorescent dying overhead, "
            "half her face in shadow, low-key practical light, shallow depth of field, unease",
            "almost static hold, subtle camera breathe, single light flicker then settle",
            "hard_cut",
        ),
        # ACT 2 — CONFLICT
        (
            "Those footsteps aren't yours.",
            f"{lock}, ACT2 CONFLICT: over-shoulder looking back into empty dark hallway, "
            "dramatic shadow play, claustrophobic framing, something unseen behind her, dread",
            "slow reluctant push toward the darkness behind her, delayed reveal, soft shake",
            "fade_to_black",
        ),
        (
            "The elevator opens. Nobody.",
            f"{lock}, ACT2 CONFLICT: standing before open empty elevator, sickly yellow car light, "
            "her silhouette in doorway, low-key contrast, impossible invitation, dread escalating",
            "doors finish opening and hold, ultra slow push into the empty car, no sudden moves",
            "hard_cut",
        ),
        # ACT 3 — CLIMAX
        (
            "Don't turn around.",
            f"{lock}, ACT3 CLIMAX build: extreme close-up eye and cheek, phone glow as only key light, "
            "sweat, shallow DOF, black void behind her shoulder, held breath before violence",
            "glacial push-in on the eye, micro shake, almost no motion until the end of the beat",
            "smash_cut",
        ),
        (
            "LOOK.",
            f"{lock}, ACT3 CLIMAX payoff JUMP SCARE: ONE pale figure lunges inches from lens, "
            "harsh sudden key light, mouth open, black eyes, photoreal shock frame, "
            "no extra limbs no double head, single creature only",
            "violent snap zoom into the face after a long stillness, impact then cut-black energy",
            "none",
        ),
    ]
    scenes = [
        Scene(narration=n, visual_prompt=v, motion_prompt=m, transition_to_next=t)
        for n, v, m, t in beats
    ]
    scenes = _with_transitions(scenes)
    return _with_trinity(
        Screenplay(
            title="Hospital Corridor — 30s Horror",
            scenes=scenes,
            raw={
                "fallback": True,
                "emotional_tone": "slow-burn dread → sudden violation",
                "act_map": {"setup": [1, 2], "conflict": [3, 4], "climax": [5, 6]},
                "narrative_engine": "cinematic_3act",
                "transitions": [s.transition_to_next for s in scenes],
            },
        ),
        character_bible=lock,
        location_lock="abandoned hospital corridor at night, flickering fluorescents",
        prop_bible="empty elevator doors and unseen second set of footsteps",
        lighting_bible="sickly fluorescent flicker, hard side-key, deep corridor shadows",
    )


def _fallback_scifi_screenplay(job: TopicJob) -> Screenplay:
    """3-act photoreal sci-fi — dense unique VO + Act-2 solitary isolation."""
    eng = getattr(config, "CHARACTER_BIBLE_A", "South Asian woman engineer in a tan trench coat")
    # Prefer engineer look for server-farm story while keeping bible wardrobe DNA
    lock = (
        f"{eng}, mid-20s systems engineer, ID badge lanyard, photoreal face, "
        "identical wardrobe every shot, single consistent identity"
    )
    beats = [
        (
            "Deep under the city the server farm hums awake, and she realizes the racks are breathing back.",
            f"{lock}, ACT1 SETUP: subterranean server farm corridor, endless cold blue LED racks, "
            "over-the-shoulder and profile angles looking at server screens, never looking at camera, "
            "candid cinematic staging interacting with environment, "
            "volumetric fog, low-key cyan practicals, claustrophobic vanishing point, "
            "photorealistic cinematic 8k, 35mm film still, rising machine dread",
            "slow dolly forward between glowing racks, subtle camera breathe, tension hold",
            "hard_cut",
        ),
        (
            "Alone between the blinking towers she hears her own voice returned as something colder.",
            f"SUBJECT: Solitary shot of ONLY {eng}. Completely isolated, wide staging, "
            "no other characters in the frame, ACT2 ESCALATION: single engineer tiny in frame "
            "amid towering server racks, looking away, solitary, sad expression, distance, "
            "profile shot never facing lens, harsh rim light, empty aisle, "
            "photorealistic cinematic 8k, emotional isolation",
            "slow crane down revealing how alone she is, almost static ache",
            "fade_to_black",
        ),
        (
            "When the red alarms bloom she chooses the kill switch, and the machine finally learns fear.",
            f"{lock}, ACT3 CLIMAX: emergency red wash over blue racks, her hand on the kill switch, "
            "over-the-shoulder looking at the console, never looking at camera, "
            "ultra-sharp focus, shallow DOF on the hand then crisp wide pullback as lights die, "
            "photorealistic cinematic 8k, definitive payoff",
            "snap push-in to the hand on the switch then slow pull back into darkness",
            "none",
        ),
    ]
    scenes = [
        Scene(narration=n, visual_prompt=v, motion_prompt=m, transition_to_next=t)
        for n, v, m, t in beats
    ]
    scenes = _with_transitions(scenes)
    return _with_trinity(
        Screenplay(
            title="Rogue AI — Subterranean Server Farm",
            scenes=scenes,
            raw={
                "fallback": True,
                "narrative_engine": "cinematic_3act_scifi",
                "transitions": [s.transition_to_next for s in scenes],
            },
        ),
        character_bible=lock,
        location_lock="subterranean server farm corridor, cold cyan LED racks, volumetric fog",
        prop_bible="rogue AI kill-switch console with blooming red alarms",
        lighting_bible="cold cyan LED practicals, hard side-key, deep shadows, red alarm wash",
    )


def _fallback_analog_phone_reel(job: TopicJob) -> Screenplay:
    """12s high-retention analog-horror Reel — continuous POV, glitch at 6s, loopable end."""
    overlay = extract_text_overlay(job.topic) or str(
        getattr(config, "DEFAULT_RAW_TEXT_OVERLAY", "Check your phone. Time is running out.")
    )
    clock_pos = str(
        getattr(
            config,
            "REEL_CLOCK_POSITIVE",
            "(standard rectangular digital smartphone clock, HH:MM time format, clear glowing typography:1.3)",
        )
    )
    cont_pos = str(
        getattr(
            config,
            "REEL_CONTINUITY_POSITIVE",
            "(locked off camera, static POV, nightstand remains in frame:1.2)",
        )
    )
    char = (
        "POV first-person only, no face visible, viewer as sleepless person in bed, "
        "hands never entering frame"
    )
    loc = (
        "dark minimalist bedroom at night, nightstand in foreground, empty wall, "
        "liminal quiet interior, no clutter"
    )
    prop_normal = (
        "smartphone upright on nightstand displaying standard rectangular digital lock-screen "
        "clock ONLY normal time 03:14 HH:MM with colon, cold blue screen glow, readable white digits, "
        "never 25:66, never impossible time, never circular clock widget, never stacked two-line digits"
    )
    prop_glitch = (
        "smartphone upright on nightstand SAME angle, lock-screen shows impossible time 25:66 HH:MM "
        "with colon clearly readable, cold blue intensifies, never circular clock, never single digit"
    )
    light = (
        "sole practical: cold blue smartphone screen as key light, deep bedroom shadows, "
        "Rembrandt falloff into black, shadows stretch and deepen at the glitch, "
        "digits stay readable no bloom blowout"
    )
    beats = [
        (
            overlay,
            f"{char}, {loc}, {prop_normal}, {light}, {clock_pos}, {cont_pos}, "
            "SETUP: extreme POV locked on phone on nightstand, digital clock readable NORMAL "
            "time 03:14 HH:MM rectangular digits with colon, shallow DOF, dust in blue light, "
            "photorealistic cinematic 8k, analog horror liminal dread, no hands in frame, "
            "SENSORY weathered nightstand wood microscopic dust caustic phone glow",
            "very slow creep-in toward the phone screen, almost imperceptible push, "
            "locked tripod POV, nightstand stays in frame",
            "hard_cut",
        ),
        (
            overlay,
            f"{char}, {loc}, {prop_glitch}, {light}, {clock_pos}, {cont_pos}, "
            "PAYOFF SAME ANGLE: identical POV on the SAME nightstand phone, "
            "lock-screen digits violently glitch scramble then freeze on impossible time 25:66, "
            "ambient shadows stretch and deepen, cold blue intensifies, photorealistic cinematic 8k, "
            "analog horror, no face, no handheld, PROP clearly shows 25:66 HH:MM with colon",
            "static hold then micro-shake as digits scramble, shadows expand, settle on 25:66, "
            "locked off camera, nightstand remains",
            "none",
        ),
    ]
    scenes = [
        Scene(narration=n, visual_prompt=v, motion_prompt=m, transition_to_next=t)
        for n, v, m, t in beats
    ]
    scenes = _with_transitions(scenes, ["hard_cut", "none"])
    return _with_trinity(
        Screenplay(
            title="25:66 — Nightstand Clock",
            scenes=scenes,
            raw={
                "fallback": True,
                "llm_disabled": True,
                "narrative_engine": "analog_phone_12s_reel",
                "reel_profile": "analog_phone_12s",
                "director_mode": "raw",
                # False: beat0=03:14 must not seed beat1 — digit change is the scare
                "continuity_i2v": False,
                "text_overlay": overlay,
                "caption_position": "top",
                "target_duration_sec": 12.0,
                "glitch_at_sec": 6.0,
                "loop_end_sec": 11.9,
                "facebook_caption": (
                    "I literally froze when the clock changed. Looked at my own wall clock "
                    "right after to make sure. Did you catch the numbers at 0:06?"
                ),
                "hashtags": (
                    "#analoghorror #liminalspace #creepy #glitch #scarystories #paranormal #loop"
                ),
                "transitions": [s.transition_to_next for s in scenes],
            },
        ),
        character_bible=char,
        location_lock=loc,
        prop_bible=prop_normal,
        lighting_bible=light,
    )


def _is_analog_phone_reel_topic(topic: str) -> bool:
    t = (topic or "").lower()
    keys = (
        "25:66", "2566", "nightstand", "lock screen", "analog horror",
        "phone clock", "smartphone clock", "bedroom at night", "creepy reel",
        "clock glitch", "impossible time",
    )
    return any(k in t for k in keys)


def _is_echo_chamber_reel_topic(topic: str) -> bool:
    t = (topic or "").lower()
    keys = (
        "echo chamber", "split-screen", "split screen", "maritime map forum",
        "penthouse balcony", "museum map exhibit",
    )
    return any(k in t for k in keys)


def _is_wingsuit_canyon_topic(topic: str) -> bool:
    t = (topic or "").lower()
    if "wingsuit" in t:
        return True
    if "canyon" in t and any(k in t for k in ("flyer", "flight", "soar", "breakneck", "drone")):
        return True
    if "point-of-view" in t and "canyon" in t:
        return True
    return False


def _is_usa_sports_quiz_topic(topic: str) -> bool:
    t = (topic or "").lower()
    if "quiz" not in t and "trivia" not in t:
        return False
    keys = (
        "usa sports", "us sports", "american sports", "nfl", "nba", "mlb",
        "super bowl", "sports quiz", "sports trivia",
    )
    return any(k in t for k in keys)


def _is_music_video_lyric_topic(topic: str) -> bool:
    t = (topic or "").lower()
    if "music_video_lyric_180s" in t or "final_hit_song" in t:
        return True
    if "music video" in t or "lyric mv" in t or "lyric music video" in t:
        return True
    return False


def _fallback_music_video_lyric(job: TopicJob) -> Screenplay:
    """Full ~180s 16:9 lyric MV v2 — distinct locations, locked male identity, Wan peaks."""
    job.ratio = "16:9"
    # Hard identity — baked into every plate (skip default romance duo bible)
    him = (
        "SAME young man every shot, mid-20s South Asian male, short dark wavy hair, "
        "light stubble, charcoal hoodie, identical face and wardrobe, solitary only, "
        "never a woman, never gender swap"
    )
    frame = (
        "photoreal cinematic 8k, full-bleed 16:9 frame edge to edge, "
        "NO letterbox, NO black bars, NO cinema bars, NO text in image, NO logos"
    )
    night = "same rainy late-night city world, cool teal practicals, warm streetlight gold"
    master = r"C:\Users\user\Documents\SunoX\workspace\FINAL_HIT_SONG.wav"
    lyrics = r"C:\Users\user\Documents\SunoX\workspace\lyric_alignment.json"
    edges = [0.0, 7.4, 21.0, 35.0, 50.0, 57.1, 81.9, 100.0, 118.1, 125.0, 149.0, 163.6, 180.0]
    beat_durations = [round(edges[i + 1] - edges[i], 2) for i in range(12)]
    # Short Wan peaks only (≤65 frames in pipeline) — chorus energy without OOM
    wan_idxs = {4, 5, 8, 9, 10, 11}
    # Stronger Ken Burns zoom on chorus holds
    beat_plan = []
    for i in range(12):
        eng = "wan" if i in wan_idxs else "ken_burns"
        zoom = 1.10 if i in {5, 9, 11} else (1.07 if eng == "ken_burns" else 1.06)
        beat_plan.append({"engine": eng, "wan": i in wan_idxs, "zoom_end": zoom})

    # Each plate = DISTINCT location DNA (reject bedroom clones)
    plates = [
        (
            "City lights blur through the window glass",
            (
                f"{him}, LOCATION: rainy apartment WINDOW only, over-shoulder looking out, "
                f"city lights blur through wet glass, curtains, radiator under sill, "
                f"NO bed in frame, NO phone in hands, {night}, {frame}"
            ),
            "slow push into rain-streaked glass, bokeh drift, music-video intro push",
        ),
        (
            "2 a.m. kitchen, blue phone glow",
            (
                f"{him}, LOCATION: kitchen counter only, 2 a.m., blue phone glow on his hands, "
                f"cold coffee mug, unread replies vibe, tile backsplash, "
                f"NO bedroom, NO bed, {night}, {frame}"
            ),
            "subtle handheld breathe, phone light flicker, verse intimacy",
        ),
        (
            "Hoodie on the hallway chair",
            (
                f"{him} as soft silhouette at hallway edge OR empty frame focus on prop, "
                f"LOCATION: narrow apartment HALLWAY, wooden chair, charcoal hoodie draped on chair, "
                f"cold coffee on side table, perspective corridor, "
                f"NO bedroom, NO bed, NO train, {night}, {frame}"
            ),
            "slow lateral drift past hoodie on chair, shallow DOF, prop storytelling",
        ),
        (
            "Almost-kiss memories in the quiet bedroom",
            (
                f"{him} absent or extreme edge of frame, LOCATION: bedroom EMPTY SIDE OF BED only, "
                f"streetlight gold through blinds on vacant pillow, rumpled sheets memory, "
                f"NO second person, {night}, {frame}"
            ),
            "gentle push across empty pillow, dust in gold light, ache",
        ),
        (
            "Don't need a spotlight — just one honest sentence",
            (
                f"{him}, LOCATION: bathroom mirror / hallway mirror pre-chorus, "
                f"tight over-shoulder, breath before confession, face partial in reflection, "
                f"NO bed, NO train car, {night}, {frame}"
            ),
            "cinematic push-in on shoulders, held breath, rising pre-chorus energy",
        ),
        (
            "I never said it out loud",
            (
                f"{him}, LOCATION: rooftop or fire-escape overlooking wet city at night, "
                f"chorus lift, wind in hoodie, city glow behind him, emotional wide then tighter, "
                f"NO bedroom interior, NO sitting on bed, {night}, {frame}"
            ),
            "rising camera energy, light bloom, chorus punch then settle",
        ),
        (
            "Streetlight paints gold on your side of the bed",
            (
                f"LOCATION: bedroom empty bed ONLY, streetlight gold stripe on vacant side, "
                f"blinds shadow pattern, mug on nightstand, {him} not required in frame, "
                f"NO kitchen, NO train, {night}, {frame}"
            ),
            "slow pan across gold light on empty sheets, longing",
        ),
        (
            "Late train home in headphones",
            (
                f"{him}, LOCATION: night subway/metro TRAIN CAR interior ONLY, "
                f"over-ear headphones, window reflection of passing city lights, poles and seats, "
                f"crowded soft bokeh strangers out of focus, "
                f"FORBIDDEN: bedroom, bed, apartment kitchen, hallway chair, {frame}"
            ),
            "train sway, city lights streaking on glass, verse-2 motion",
        ),
        (
            "Draft the confession, then delete the draft",
            (
                f"{him} hands and phone ECU only, LOCATION: phone screen close-up typing then deleting "
                f"a confession draft, blue UI glow, thumbs, "
                f"background hint of cafe window or train seat NOT bedroom bed, {frame}"
            ),
            "nervous handheld micro-moves, screen glow pulse, pre-chorus 2",
        ),
        (
            "I never said it out loud — chorus return",
            (
                f"{him}, LOCATION: apartment DOORWAY / threshold only, hand on doorframe, "
                f"almost-stayed moment, hallway light behind, emotional second chorus, "
                f"NO bed, NO train seats, {night}, {frame}"
            ),
            "push through doorway, stronger light lift, chorus return energy",
        ),
        (
            "Maybe you'll leave, maybe you'll stay",
            (
                f"{him}, LOCATION: rain-soaked sidewalk outside building entrance, bridge resolve, "
                f"facing streetlights, decisive stillness, hoodie hood down, "
                f"NO bedroom, NO bed, {night}, {frame}"
            ),
            "held frame then slight push-in, bridge resolve, honest stillness",
        ),
        (
            "I said it out loud… and I hope you hear",
            (
                f"{him}, LOCATION: clear apartment WINDOW outro, face toward glass, hopeful, "
                f"city lights soft, voice clear energy, SAME man as every prior shot, "
                f"NO gender swap, NO woman, {night}, {frame}"
            ),
            "slow settle on window, soft hope bloom, gentle pullback",
        ),
    ]
    scenes = []
    for i, (narr, visual, motion) in enumerate(plates):
        scenes.append(
            Scene(
                narration=narr,
                visual_prompt=visual,
                motion_prompt=motion,
                transition_to_next="hard_cut" if i < len(plates) - 1 else "none",
            )
        )
    # MV edit feel: smash into choruses
    trans = ["hard_cut"] * 11 + ["none"]
    for i in (4, 5, 8, 9):  # into pre/chorus peaks
        if i < len(trans) - 1:
            trans[i] = "smash_cut"
    scenes = _with_transitions(scenes, trans)
    return Screenplay(
        title="I Never Said It Out Loud — Lyric MV v2",
        scenes=scenes,
        raw={
            "fallback": True,
            "llm_disabled": True,
            "director_mode": "raw",
            "narrative_engine": "music_video_lyric_180s",
            "reel_profile": "music_video_lyric_180s",
            "mv_version": 2,
            "skip_act_emotion": True,
            "skip_character_bible": True,  # identity baked into plates (blocks romance duo)
            "burn_captions": True,
            "caption_mode": "lyric_cues",
            "caption_position": "bottom",
            "continuity_i2v": False,
            "restart_comfy_before_wan": True,
            "target_duration_sec": 180.0,
            "loop_end_sec": 180.0,
            "master_audio": master,
            "lyric_alignment": lyrics,
            "beat_durations": beat_durations,
            "beat_plan": beat_plan,
            "cinematic_grade": "music_soft",
            "transitions": [s.transition_to_next for s in scenes],
        },
        character_bible=him,
        location_lock=(
            "multi-location night confession world: window, kitchen, hallway, empty bed, "
            "mirror, rooftop/fire-escape, metro train, doorway, rainy sidewalk — never one bedroom loop"
        ),
        prop_bible="charcoal hoodie, cold coffee, blue phone, headphones, empty pillow, doorframe",
        lighting_bible="cool teal practicals, warm streetlight gold, wet glass bokeh, never pure silhouette",
    )


def _fallback_usa_sports_quiz(job: TopicJob) -> Screenplay:
    """12s English USA sports quiz Reel — Q → options → answer."""
    stadium = (
        "photoreal NFL football stadium at night, packed crowd, bright floodlights, "
        "emerald turf, jumbotron glow, cinematic sports broadcast look, no readable logos, "
        "no jersey numbers, no text in frame"
    )
    q = "Which NFL team has won the most Super Bowls?"
    opts = "A) Patriots  ·  B) Steelers  ·  C) Cowboys"
    ans = "B) Steelers — 6 Super Bowl titles"

    scenes = [
        Scene(
            narration=q,
            visual_prompt=(
                f"epic wide establishing shot of {stadium}, dramatic sky, "
                f"high-octane sports atmosphere, photoreal 8k, no text overlays in image"
            ),
            motion_prompt="slow cinematic drone push over stadium, crowd ambient sway, light bloom",
            transition_to_next="hard_cut",
        ),
        Scene(
            narration=opts,
            visual_prompt=(
                f"tighter cinematic angle on {stadium}, jumbotron glow reflecting on crowd, "
                f"tense quiz energy, same night game world, photoreal 8k, no text in image"
            ),
            motion_prompt="subtle handheld urgency, light camera push, crowd pulse",
            transition_to_next="hard_cut",
        ),
        Scene(
            narration=ans,
            visual_prompt=(
                f"celebration payoff in {stadium}, confetti in floodlights, roaring crowd silhouette, "
                f"triumphant sports broadcast finale, photoreal 8k, no text in image"
            ),
            motion_prompt="confetti drift, slight whip-pan energy then settle, lens flare punch",
            transition_to_next="none",
        ),
    ]
    scenes = _with_transitions(scenes, ["hard_cut", "hard_cut", "none"])
    return Screenplay(
        title="USA Sports Quiz — Super Bowl Kings",
        scenes=scenes,
        raw={
            "fallback": True,
            "llm_disabled": True,
            "director_mode": "raw",
            "narrative_engine": "usa_sports_quiz_12s",
            "reel_profile": "usa_sports_quiz_12s",
            "skip_act_emotion": True,
            "skip_character_bible": True,
            "burn_captions": True,
            "caption_mode": "per_beat",
            "caption_position": "center",
            "continuity_i2v": False,
            "audio_profile": "lofi_chime",
            "restart_comfy_before_wan": True,
            "target_duration_sec": 12.0,
            "loop_end_sec": 12.0,
            "loop_end_silence": 0.35,
            "collapse_at_sec": 5.0,
            "beat_durations": [5.0, 4.0, 3.0],
            "transitions": [s.transition_to_next for s in scenes],
        },
        location_lock=stadium,
        prop_bible="stadium lights, turf, jumbotron glow, confetti on finale",
        lighting_bible="night game floodlights, bright readable scene, never pure silhouette",
    )


def _fallback_wingsuit_canyon(job: TopicJob) -> Screenplay:
    """15s one-shot Reel — one Flux plate + continuity I2V (Wan 480). No cut DNA resets."""
    suit = str(
        getattr(
            config,
            "ACTION_WINGSUIT_POSITIVE",
            "REAL fabric wingsuit: nylon stretched between arms and legs",
        )
    )
    flyer = (
        f"SAME wingsuit flyer locked for the entire continuous take: athletic adult, {suit}, "
        "matte black suit with small orange reflective panels on arms/legs only, "
        "sealed black aerodynamic helmet dark visor DOWN, compact parachute container, "
        "dark gloves boots, photoreal Red Bull TV / GoPro documentary look, "
        "FORBIDDEN: butterfly, monarch, insect, bat, dragon, or mechanical wings"
    )
    canyon = (
        "narrow jagged granite mountain canyon, vertical cliff walls, sparse scrub, "
        "deep gorge with turquoise river far below, distant snow peaks, harsh alpine sun"
    )
    velocity = (
        "extreme velocity, heavy motion blur on rock walls, wind shear, "
        "subtle handheld camera shake, dangerously close to cliffs"
    )
    # Single locked camera language for continuity I2V (one world, one suit).
    plate = (
        f"cinematic drone chase CLOSE behind {flyer}, continuous proximity flight through {canyon}, "
        f"camera locked above-and-behind sports broadcast angle, within meters of jagged cliffs, "
        f"{velocity}, {suit}, leg-wing nylon between thighs, arm-wing nylon stretched flat under arms, "
        f"technical skydiving fabric only — no butterfly, no feathers, no bird wings, no mechanical wings, "
        f"readable suit with soft fill light, photoreal Red Bull TV documentary 8k, no text, no HUD"
    )

    scenes = [
        Scene(
            narration="One continuous line through the gorge — no cut, no mercy.",
            visual_prompt=plate,
            motion_prompt=(
                "continuous high-speed chase follow, heavy motion blur, "
                "subtle camera shake, rocks whipping past"
            ),
            transition_to_next="hard_cut",
        ),
        Scene(
            narration="Same flight, tighter to the granite — the line holds.",
            visual_prompt=(
                f"{plate}, SAME locked camera and flyer identity, banking slightly with the flyer, "
                f"even closer to the cliff face, continuous motion only"
            ),
            motion_prompt=(
                "same continuous chase, slight bank, cliff proximity rush, "
                "motion blur, micro camera shake — no cut, no new angle invent"
            ),
            transition_to_next="hard_cut",
        ),
        Scene(
            narration="Same chase to the sunlit exit — one take to the ridge.",
            visual_prompt=(
                f"{plate}, SAME locked camera and flyer identity, push deeper into the gorge "
                f"toward sunlit peaks, continuous motion only"
            ),
            motion_prompt=(
                "same continuous chase accelerating, lens flare bloom ahead, "
                "residual shake, extreme speed through the gorge exit"
            ),
            transition_to_next="none",
        ),
    ]
    scenes = _with_transitions(scenes, ["hard_cut", "hard_cut", "none"])
    return Screenplay(
        title="Wingsuit Canyon — 15s One-Shot",
        scenes=scenes,
        raw={
            "fallback": True,
            "llm_disabled": True,
            "director_mode": "raw",
            "narrative_engine": "wingsuit_oneshot_15s",
            "reel_profile": "wingsuit_oneshot_15s",
            "action_flight": True,
            "skip_act_emotion": True,
            "identity_lock_from_scene1": True,
            "suit_bible": False,
            "fpv_scene_indices": [],
            "burn_captions": False,
            "continuity_i2v": True,
            "audio_profile": "wind_rush",
            "restart_comfy_before_wan": True,
            "target_duration_sec": 15.0,
            "loop_end_sec": 15.0,
            "loop_end_silence": 0.35,
            "whoosh_at_sec": 5.0,
            "beat_durations": [5.0, 5.0, 5.0],
            "transitions": [s.transition_to_next for s in scenes],
        },
        character_bible=flyer,
        location_lock=canyon,
        prop_bible="realistic fabric wingsuit, black helmet visor down, parachute container",
        lighting_bible=(
            "harsh alpine sun, lens flares through peaks, deep canyon shadows, "
            "readable suit color even in shade — never pure silhouette"
        ),
    )


def _fallback_echo_chamber_reel(job: TopicJob) -> Screenplay:
    """12s Echo Chamber — two isolated panel clips composited, then reunion."""
    overlay = extract_text_overlay(job.topic) or (
        "When the only one who understands your obsession, finally understands you."
    )
    overlay_clean = " ".join(overlay.replace("🗺️", "").replace("💫", "").split()).strip()
    if "understands your obsession" not in overlay_clean:
        overlay_clean = (
            "When the only one who understands your obsession, finally understands you."
        )
    overlay_show = overlay if ("🗺️" in overlay or "💫" in overlay) else (
        overlay_clean + " 🗺️💫"
    )
    face = str(
        getattr(
            config,
            "FACE_FILL_POSITIVE",
            "(soft front fill light, readable facial expressions, studio lighting, glowing faces:1.3)",
        )
    )

    # THREE generation plates — MoviePy stacks 0+1 into true vertical split
    office = (
        f"SINGLE SUBJECT ONLY, one person with glasses in a dim cluttered home office at night, "
        f"focused on desktop computer showing ancient maritime map forum, rapid typing, "
        f"small genuine smile, notification blink on screen, warm desk lamp practical, "
        f"photorealistic cinematic 8k, {face}, no second person, no split-screen, "
        f"no text burned in image"
    )
    penthouse = (
        f"SINGLE SUBJECT ONLY, one person on a sleek contemporary penthouse balcony at night, "
        f"holding coffee cup, laptop showing the SAME ancient maritime map forum thread, "
        f"thoughtful pause then decisive reply, cool city rim light, "
        f"photorealistic cinematic 8k, {face}, no second person, no split-screen, "
        f"no text burned in image"
    )
    reunion = (
        f"two people standing together in a quiet museum cartography map exhibit hall, "
        f"soft front fill light on BOTH faces, readable facial expressions, initially awkward "
        f"then smiling broadly recognizing each other's passion, ancient maps on walls, "
        f"photorealistic cinematic 8k, intimate modern romance, {face}, "
        f"NOT silhouette, NOT backlit only, faces clearly lit, no text burned in image"
    )

    scenes = [
        Scene(
            narration=overlay_show,
            visual_prompt=office,
            motion_prompt="rapid typing, smile forming, notification blink, locked desk POV",
            transition_to_next="hard_cut",
        ),
        Scene(
            narration=overlay_show,
            visual_prompt=penthouse,
            motion_prompt="thoughtful pause, coffee sip, decisive reply tap, city bokeh hold",
            transition_to_next="hard_cut",
        ),
        Scene(
            narration=overlay_show,
            visual_prompt=reunion,
            motion_prompt="awkward micro-shift then warm mutual smiles, gentle push-in, loop hold",
            transition_to_next="none",
        ),
    ]
    scenes = _with_transitions(scenes, ["hard_cut", "hard_cut", "none"])
    return _with_trinity(
        Screenplay(
            title="Echo Chamber — Forum Romance",
            scenes=scenes,
            raw={
                "fallback": True,
                "llm_disabled": True,
                "director_mode": "raw",
                "continuity_i2v": False,
                "reel_profile": "echo_chamber_12s",
                "audio_profile": "lofi_chime",
                "text_overlay": overlay_show,
                "caption_position": "center",
                "burn_captions": False,
                "face_fill": True,
                "target_duration_sec": 12.0,
                "collapse_at_sec": 8.0,
                # Per generation clip (office, penthouse, reunion)
                "beat_durations": [8.0, 8.0, 3.9],
                "panel_specs": [
                    {"ratio": "16:9", "role": "top", "face_fill": True},
                    {"ratio": "16:9", "role": "bottom", "face_fill": True},
                    {"ratio": "9:16", "role": "full", "face_fill": True},
                ],
                # Delivery timeline after MoviePy vertical stack
                "compose_plan": [
                    {
                        "type": "vsplit",
                        "sources": [0, 1],
                        "duration": 8.0,
                        "transition_to_next": "smash_cut",
                    },
                    {
                        "type": "single",
                        "sources": [2],
                        "duration": 3.9,
                        "transition_to_next": "none",
                    },
                ],
                "loop_end_sec": 11.9,
                "loop_end_silence": 0.5,
                "transitions": [s.transition_to_next for s in scenes],
            },
        ),
        character_bible=(
            "two solitary strangers who only know each other through an online forum; "
            "generate as SEPARATE single-subject plates for the split, then together for reunion"
        ),
        location_lock=(
            "panel A: dim cluttered home office; panel B: sleek penthouse balcony; "
            "reunion: quiet museum map exhibit"
        ),
        prop_bible=(
            "same ancient maritime map forum on screens, laptop, coffee cup, museum maps"
        ),
        lighting_bible=(
            "soft front fill on faces always; office warm lamp; balcony cool city rim; "
            "museum soft overheads + fill — never silhouette"
        ),
    )


def _build_raw_screenplay(job: TopicJob) -> Screenplay:
    """100% LLM-off screenplay from the user prompt (+ optional [TEXT OVERLAY])."""
    if _is_analog_phone_reel_topic(job.topic):
        return _fallback_analog_phone_reel(job)
    if _is_echo_chamber_reel_topic(job.topic):
        return _fallback_echo_chamber_reel(job)
    if _is_wingsuit_canyon_topic(job.topic):
        return _fallback_wingsuit_canyon(job)
    if _is_usa_sports_quiz_topic(job.topic):
        return _fallback_usa_sports_quiz(job)
    if _is_music_video_lyric_topic(job.topic):
        return _fallback_music_video_lyric(job)

    overlay = extract_text_overlay(job.topic) or str(
        getattr(config, "DEFAULT_RAW_TEXT_OVERLAY", "Check your phone. Time is running out.")
    )
    body = strip_text_overlay_block(job.topic) or job.topic
    # Strip section headers for cleaner Flux positives
    body = re.sub(
        r"\[(?:VISUAL\s*&\s*MOTION|AUDIO\s*STREAM|TEXT\s*OVERLAY)\]",
        " ",
        body,
        flags=re.I,
    )
    body = " ".join(body.split())
    cont_pos = str(getattr(config, "REEL_CONTINUITY_POSITIVE", ""))
    visual_base = (
        f"{body}, {cont_pos}, photorealistic cinematic 8k, "
        "locked framing DNA across beats"
    ).strip(", ")
    scenes = [
        Scene(
            narration=overlay,
            visual_prompt=f"{visual_base}, beat 1 establishing",
            motion_prompt="slow cinematic motion, subtle ambient life",
            transition_to_next="hard_cut",
        ),
        Scene(
            narration=overlay,
            visual_prompt=f"{visual_base}, beat 2 payoff, same world DNA",
            motion_prompt="intensify then settle for loop hold",
            transition_to_next="none",
        ),
    ]
    scenes = _with_transitions(scenes, ["hard_cut", "none"])
    return Screenplay(
        title=(body[:80] or "Raw Reel").strip(),
        scenes=scenes,
        raw={
            "fallback": True,
            "llm_disabled": True,
            "director_mode": "raw",
            "continuity_i2v": True,
            "reel_profile": "raw_reel_12s",
            "audio_profile": "lofi_chime",
            "text_overlay": overlay,
            "caption_position": "center",
            "target_duration_sec": 12.0,
            "collapse_at_sec": 8.0,
            "beat_durations": [8.0, 3.9],
            "loop_end_sec": 11.9,
            "loop_end_silence": 0.5,
            "transitions": [s.transition_to_next for s in scenes],
        },
        location_lock="locations exactly as specified in user prompt",
        prop_bible="props exactly as specified in user prompt",
        lighting_bible="lighting exactly as specified in user prompt",
    )


def generate_screenplay(job: TopicJob, scene_count: int | None = None) -> Screenplay:
    n = scene_count or config.SCENES_PER_VIDEO
    topic_l = job.topic.lower()
    # --mode raw / pipeline:raw → LLM fully disabled
    if getattr(job, "director_mode", "story") == "raw":
        return _build_raw_screenplay(job)
    # Locked full-song lyric music video (before love/horror LLM paths)
    if _is_music_video_lyric_topic(job.topic):
        return _fallback_music_video_lyric(job)
    # Locked USA sports quiz Reel (before LLM)
    if _is_usa_sports_quiz_topic(job.topic):
        return _fallback_usa_sports_quiz(job)
    # Locked 15s wingsuit action (before LLM — kills Act-2 drama leak)
    if _is_wingsuit_canyon_topic(job.topic):
        return _fallback_wingsuit_canyon(job)
    # Locked 12s analog-horror phone reel (before generic hospital horror)
    if _is_analog_phone_reel_topic(job.topic):
        return _fallback_analog_phone_reel(job)
    # Locked cinematic dinner date (before generic love — needs anti-kiss / empty room)
    if _is_dinner_date_topic(job.topic):
        sp = _fallback_dinner_date_screenplay(job)
        if n and len(sp.scenes) > n:
            sp.scenes = _with_transitions(sp.scenes[:n])
        return sp
    # Locked cinematic romance — photoreal 8-beat ~120s (priority over generic LLM for love topics)
    love_keys = ("love", "romance", "romantic", "metro love", "प्यार", "इश्क", "मोहब्बत", "प्रेम", "लव")
    if any(k in topic_l or k in job.topic for k in love_keys):
        sp = _fallback_love_screenplay(job)
        # Timed 120s romance keeps full beat sheet — never truncate to SCENES_PER_VIDEO
        if (sp.raw or {}).get("reel_profile") == "romance_love_120s":
            return sp
        if n and len(sp.scenes) > n:
            sp.scenes = _with_transitions(sp.scenes[:n])
        return sp
    # Locked cinematic horror arc when topic is explicitly horror (still 3-act, paced)
    if "horror" in topic_l or "jumpscare" in topic_l or "jump scare" in topic_l:
        sp = _fallback_horror_screenplay(job)
        if n and len(sp.scenes) > n:
            if n == 3 and len(sp.scenes) >= 6:
                sp.scenes = _with_transitions(
                    [sp.scenes[0], sp.scenes[2], sp.scenes[5]],
                    ["hard_cut", "smash_cut", "none"],
                )
            else:
                sp.scenes = _with_transitions(sp.scenes[:n])
        return sp
    # Sci-fi / thriller: try live LLM first (strict JSON + retries), fallback only after failure
    scifi_keys = (
        "rogue ai", "server farm", "artificial intelligence", "ai awakening",
        "cyber", "android", "neon", "detective", "noir",
    )
    prefers_scifi_fallback = any(k in topic_l for k in scifi_keys) or (
        "ai" in topic_l and "server" in topic_l
    )

    system = _director_system_prompt(job, n)
    payload = {
        "model": config.OLLAMA_MODEL,
        "prompt": f"{system}\n\nTopic: {job.topic}\n\nRespond with JSON only.",
        "format": "json",  # enforce strict JSON from Ollama
        "stream": False,
        "options": {"temperature": 0.55},
    }
    max_retries = max(3, int(getattr(config, "OLLAMA_MAX_RETRIES", 3)))
    last_err: Exception | None = None
    for attempt in range(max_retries):
        try:
            resp = requests.post(config.OLLAMA_URL, json=payload, timeout=600)
            resp.raise_for_status()
            body = resp.json()
            raw_text = body.get("response") or "{}"
            data = _extract_json_object(raw_text)
            if not isinstance(data, dict):
                raise ValueError(f"Ollama JSON was not an object (attempt {attempt + 1})")
            screenplay = _parse_screenplay(data, job.topic, job.style)
            if screenplay.scenes and all(
                (s.narration or "").strip() and (s.visual_prompt or "").strip()
                for s in screenplay.scenes
            ):
                if n and len(screenplay.scenes) > n:
                    screenplay.scenes = screenplay.scenes[:n]
                screenplay.raw = {
                    **(screenplay.raw or {}),
                    "fallback": False,
                    "ollama_attempts": attempt + 1,
                }
                return screenplay
            last_err = ValueError(
                f"Empty/invalid scenes from Ollama (attempt {attempt + 1}/{max_retries}): "
                f"{raw_text[:240]}"
            )
        except (requests.RequestException, json.JSONDecodeError, ValueError, TypeError, KeyError) as exc:
            last_err = exc
            # Cooler retry — more deterministic JSON
            payload["options"] = {"temperature": 0.2 if attempt >= 1 else 0.35}
            continue
    # Last-resort production fallback ONLY after all retries fail
    if prefers_scifi_fallback or any(
        k in topic_l for k in ("ai", "server", "neon", "detective", "noir", "cyber")
    ):
        return _fallback_scifi_screenplay(job)
    raise RuntimeError(f"Director screenplay failed after {max_retries} retries: {last_err}")


def _flatten_prompt_field(value: Any) -> str:
    """Normalize LLM visual/motion fields that sometimes arrive as nested dict/list."""
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    if isinstance(value, dict):
        parts: list[str] = []
        # Prefer cinematic keys in a readable order
        for key in (
            "location",
            "setting",
            "characters",
            "character",
            "wardrobe",
            "face",
            "camera_movement",
            "camera",
            "lighting_cues",
            "lighting",
            "mood",
            "negative_emotional_keywords",
            "action",
            "description",
            "prompt",
        ):
            if key not in value:
                continue
            v = value[key]
            if isinstance(v, dict):
                parts.append(", ".join(f"{kk} {vv}" for kk, vv in v.items() if vv))
            elif isinstance(v, (list, tuple)):
                parts.append(", ".join(str(x) for x in v if x))
            elif v not in (None, True, False, ""):
                parts.append(str(v))
        # Booleans like photorealistic/cinematic/8k
        for key, v in value.items():
            if v is True:
                parts.append(str(key).replace("_", " "))
        leftover = []
        for key, v in value.items():
            if key in {
                "location", "setting", "characters", "character", "wardrobe", "face",
                "camera_movement", "camera", "lighting_cues", "lighting", "mood",
                "negative_emotional_keywords", "action", "description", "prompt",
            }:
                continue
            if v is True or v is False or v is None:
                continue
            if isinstance(v, (dict, list, tuple)):
                continue
            leftover.append(str(v))
        parts.extend(leftover)
        return ", ".join(p for p in parts if p)
    if isinstance(value, (list, tuple)):
        return ", ".join(_flatten_prompt_field(x) for x in value if x)
    return str(value).strip()


def _parse_screenplay(
    data: dict[str, Any],
    fallback_title: str,
    style: str = "live",
) -> Screenplay:
    scenes_raw = data.get("scenes") or []
    character_bible, location_lock, prop_bible, lighting_bible = _extract_trinity(
        data, fallback_title
    )
    # Identity lock for scenes = dynamic character_bible (NOT static duo config)
    character_lock = character_bible
    scenes: list[Scene] = []
    for item in scenes_raw:
        if not isinstance(item, dict):
            continue
        narration = str(item.get("narration") or "").strip()
        visual = _flatten_prompt_field(item.get("visual_prompt") or item.get("visual") or "")
        motion = _flatten_prompt_field(item.get("motion_prompt") or item.get("motion") or "")
        # Pull camera language from visual into motion if motion empty
        if not motion and visual:
            for cue in (
                "dolly zoom",
                "slow pan",
                "push-in",
                "push in",
                "handheld",
                "crane",
                "tracking",
                "static hold",
            ):
                if cue in visual.lower():
                    motion = cue
                    break
        if not narration and not visual:
            continue
        # Trinity prepend happens in pipeline — keep visual focused here
        if character_lock and character_lock.lower() not in visual.lower():
            visual = f"{character_lock}, {visual}" if visual else character_lock
        if "photorealistic" not in visual.lower():
            visual = f"{visual}, photorealistic, cinematic, 8k"
        visual = _enrich_visual_prompt(
            visual or "cinematic establishing shot",
            narration,
            fallback_title,
            style=style,
        )
        transition = normalize_transition(str(item.get("transition_to_next") or "hard_cut"))
        scenes.append(
            Scene(
                narration=narration or "...",
                visual_prompt=visual,
                motion_prompt=motion or "slow cinematic camera push-in, subtle ambient motion",
                transition_to_next=transition,
            )
        )
    scenes = _with_transitions(scenes)
    title = str(data.get("title") or fallback_title).strip()
    raw = dict(data) if isinstance(data, dict) else {}
    raw.update(
        {
            "character_bible": character_bible,
            "location_lock": location_lock,
            "prop_bible": prop_bible,
            "lighting_bible": lighting_bible,
        }
    )
    return Screenplay(
        title=title,
        scenes=scenes,
        raw=raw,
        character_bible=character_bible,
        location_lock=location_lock,
        prop_bible=prop_bible,
        lighting_bible=lighting_bible,
    )


def ollama_reachable() -> bool:
    try:
        r = requests.get("http://127.0.0.1:11434/api/tags", timeout=5)
        return r.ok
    except requests.RequestException:
        return False
